name: Create executables

on:
  push:
    branches:
      - master

env:
  windows_zip_name: 'Carabiner_Win_x64.zip'
  mac_dmg_name: 'Carabiner_Mac.dmg'
  mac_signing_name: "Deep Symmetry, LLC (9M6LKU948Y)"
  mac_notarization_user: "james@deepsymmetry.org"

jobs:
  build_windows:
    name: Build Windows executable
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1

    - uses: Deep-Symmetry/github-version-action@v1
      with:
        tag-var-name: release_tag

    - name: Compile and zip executable
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -g "Visual Studio 15 2017" ..
        cmake --build . --config Release
        cd bin\Release
        7z a $env:windows_zip_name Carabiner.exe
        mv $env:windows_zip_name ..\..\..

    - name: Upload Windows executable
      if: success()
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        isPrerelease: true
        assets: ${{ env.windows_zip_name }}
        github_token: ${{ github.token }}


  build_mac:
    name: Build macOS executable
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1

    - uses: Deep-Symmetry/github-version-action@v1
      with:
        tag-var-name: release_tag

    - name: Build, sign, and notarize macOS disk image
      env:
        IDENTITY_PASSPHRASE: ${{ secrets.IDENTITY_PASSPHRASE }}
        IDENTITY_P12_B64: ${{ secrets.IDENTITY_P12_B64 }}
        NOTARIZATION_PW: ${{ secrets.NOTARIZATION_PW }}
      run: zsh .github/scripts/build_dmg.zsh

    - name: Upload macOS disk image
      if: success()
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${{ env.release_tag }}
        isPrerelease: true
        assets: ${{ env.mac_dmg_name }}
        github_token: ${{ github.token }}


  succeed_if_skipped:
    name: Skipping CI
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Placate GitHub Actions
      run: echo "CI skipped but want action to succeed anyway."
